# Generated by Django 4.2.3 on 2023-07-04 14:06

import card.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('address_title', models.CharField(max_length=200)),
                ('company_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Kenya', 'Kenya'), ('uganda', 'Uganda')], max_length=30)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpertCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('first_name', models.CharField(max_length=225)),
                ('middle_name', models.CharField(blank=True, max_length=225, null=True)),
                ('last_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(upload_to='media', validators=[card.validators.validate_image_size, django.core.validators.validate_image_file_extension])),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=225)),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Kenya', 'Kenya'), ('uganda', 'Uganda')], max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('company_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.companyaddress')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
    ]
