# Generated by Django 4.2.3 on 2023-07-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertcard',
            name='card_type',
            field=models.CharField(choices=[('Landscape1', 'Landscape1'), ('Landscape2', 'Landscape2'), ('Portrait1', 'Portrait1'), ('Portrait2', 'Portrait2')], default='HII', max_length=100),
        ),
    ]
