# Generated by Django 4.2.3 on 2023-07-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertcard',
            name='city',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
