# Generated by Django 4.2.3 on 2023-07-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
