# Generated by Django 4.2.3 on 2023-07-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
