# Generated by Django 4.2.3 on 2023-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_companyaddress_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertcard',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code'),
        ),
    ]
