# Generated by Django 4.2.3 on 2023-07-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_activitylog_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='expertcard',
            options={},
        ),
        migrations.AddIndex(
            model_name='expertcard',
            index=models.Index(fields=['email'], name='card_expert_email_de5f53_idx'),
        ),
    ]
