# Generated by Django 4.2.3 on 2023-07-11 16:43

import card.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_expertcard_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertcard',
            name='profile_picture',
            field=models.ImageField(upload_to='media', validators=[card.validators.ValidateimageSize]),
        ),
    ]
