# Generated by Django 4.2.3 on 2023-07-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_expertcard_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertcard',
            name='card_type',
            field=models.CharField(blank=True, choices=[('Landscape1', 'Landscape1'), ('Landscape2', 'Landscape2'), ('Portrait1', 'Portrait1'), ('Portrait2', 'Portrait2')], max_length=100, null=True),
        ),
    ]
