# Generated by Django 4.2.3 on 2023-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_expertcard_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertcard',
            name='address_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
