# Generated by Django 4.2.3 on 2023-07-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='data',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='remarks',
        ),
    ]
