# Generated by Django 4.2.3 on 2023-07-20 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_expertcard_address_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertcard',
            name='card_vcf',
            field=models.FileField(blank=True, null=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vcf'])]),
        ),
    ]
