# Generated by Django 4.2.3 on 2023-07-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_remove_activitylog_data_remove_activitylog_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
