# Generated by Django 4.2.3 on 2023-07-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customadminuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customadminuser',
            index=models.Index(fields=['email'], name='admin_accou_email_6cb3c8_idx'),
        ),
    ]
