# Generated by Django 4.2.3 on 2023-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0002_alter_customadminuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadminuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
