# Generated by Django 4.2.3 on 2023-07-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0003_customadminuser_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadminuser',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
    ]
